sudo: false

language: java
jdk: openjdk10

before_install:
# https://github.com/travis-ci/travis-ci/issues/8408
- unset -v _JAVA_OPTIONS

install: true
script: mvn test

cache:
  directories:
  - $HOME/.m2
